//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMod
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREA_anticipo_extencion
    {
        public int id_anticipo { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public int id_tipo_anticipo { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public string estado_anticipo { get; set; }
        public string id_anticipo_softland { get; set; }
        public int C_id_cliente { get; set; }
        public int C_id_auxiliar { get; set; }
        public int C_monto { get; set; }
        public string C_glosa { get; set; }
        public string C_cuenta_contable { get; set; }
        public int id_usu_solicitud { get; set; }
        public Nullable<int> id_usu_pago { get; set; }
    }
}
