//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pay_Lenguaje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pay_Lenguaje() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication.App_GlobalResources.Pay.Lenguaje", typeof(Pay_Lenguaje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string cerrar {
            get {
                return ResourceManager.GetString("cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have a Document Viewer plugin for this browser.
        ///            No biggie... you can.
        /// </summary>
        public static string descarga_archivo_1 {
            get {
                return ResourceManager.GetString("descarga_archivo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to download the file..
        /// </summary>
        public static string descarga_archivo_2 {
            get {
                return ResourceManager.GetString("descarga_archivo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string guardar_cambios {
            get {
                return ResourceManager.GetString("guardar_cambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday of the Month.
        /// </summary>
        public static string home_cumple {
            get {
                return ResourceManager.GetString("home_cumple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string men_certifi {
            get {
                return ResourceManager.GetString("men_certifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antiquity.
        /// </summary>
        public static string men_certifi_Ant {
            get {
                return ResourceManager.GetString("men_certifi_Ant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string men_contrat {
            get {
                return ResourceManager.GetString("men_contrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string men_contrat_anex {
            get {
                return ResourceManager.GetString("men_contrat_anex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string men_contrat_contra {
            get {
                return ResourceManager.GetString("men_contrat_contra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string men_Documen {
            get {
                return ResourceManager.GetString("men_Documen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Settlement.
        /// </summary>
        public static string men_liquida {
            get {
                return ResourceManager.GetString("men_liquida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN MENU.
        /// </summary>
        public static string men_Menu_Prin {
            get {
                return ResourceManager.GetString("men_Menu_Prin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation request.
        /// </summary>
        public static string men_solvaca {
            get {
                return ResourceManager.GetString("men_solvaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Request´s.
        /// </summary>
        public static string Otras_solicitudes {
            get {
                return ResourceManager.GetString("Otras_solicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request´s.
        /// </summary>
        public static string solicitudes {
            get {
                return ResourceManager.GetString("solicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
