//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avisos
    {
        public int id_avisos { get; set; }
        public string titulo_aviso { get; set; }
        public string desc_aviso { get; set; }
        public System.DateTime fecha_aviso { get; set; }
        public int id_cliente { get; set; }
        public string aprobado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual parametros parametros { get; set; }
    }
}
