//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigPDF
    {
        public string tag { get; set; }
        public string campo { get; set; }
        public int id_cliente { get; set; }
        public string label { get; set; }
        public Nullable<int> orden { get; set; }
    }
}
