//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int id_doc { get; set; }
        public Nullable<int> id_novedad { get; set; }
        public string ruta { get; set; }
        public string nombre_original { get; set; }
        public string nombre_asignado { get; set; }
        public string categoria { get; set; }
        public int estado { get; set; }
        public Nullable<int> id_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Novedad Novedad { get; set; }
        public virtual parametros parametros { get; set; }
    }
}
