//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finiquito
    {
        public int id_baja { get; set; }
        public string nombres { get; set; }
        public string apellido { get; set; }
        public string rut { get; set; }
        public string direccion { get; set; }
        public string tipo_contrato { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public string causal { get; set; }
        public string nombre_sol { get; set; }
        public int id_novedad { get; set; }
        public Nullable<int> estado_aprov { get; set; }
    
        public virtual Novedad Novedad { get; set; }
        public virtual parametros parametros { get; set; }
    }
}
