//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresos
    {
        public int id_ing { get; set; }
        public string nombres { get; set; }
        public string apellido { get; set; }
        public string rut { get; set; }
        public string nacionalidad { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string direccion { get; set; }
        public string estado_civil { get; set; }
        public string mail { get; set; }
        public string telefono { get; set; }
        public string id_usu { get; set; }
        public int id_novedad { get; set; }
        public string isapre { get; set; }
        public string AFP { get; set; }
        public string Fonasa { get; set; }
        public string cargo { get; set; }
        public Nullable<int> estado_aprov { get; set; }
    
        public virtual Novedad Novedad { get; set; }
    }
}
