//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo_liquidaciones
    {
        public int id { get; set; }
        public int mes { get; set; }
        public int ano { get; set; }
        public bool liberado { get; set; }
        public Nullable<int> id_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
