//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remuneracion
    {
        public int id_rem { get; set; }
        public int id_novedad { get; set; }
        public string comentario { get; set; }
    
        public virtual Novedad Novedad { get; set; }
    }
}
