//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Permisos = new HashSet<Permisos>();
            this.Usuario1 = new HashSet<Usuario>();
            this.Usuario2 = new HashSet<Usuario>();
            this.Cliente1 = new HashSet<Cliente>();
        }
    
        public string id_usu { get; set; }
        public string Nom_usu { get; set; }
        public string pass_usu { get; set; }
        public int id_cliente { get; set; }
        public int id_tipo_usu { get; set; }
        public string email { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public string rut { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual tipo_usu tipo_usu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permisos> Permisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente1 { get; set; }
    }
}
