//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacaciones
    {
        public int id_vac { get; set; }
        public System.DateTime fecha_ini { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public int cant_dias { get; set; }
        public string descripcion { get; set; }
        public int id_novedad { get; set; }
        public string id_usu { get; set; }
        public int estado_aprov { get; set; }
    
        public virtual Novedad Novedad { get; set; }
    }
}
