//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOtraSolicitud
    {
        public string usuario { get; set; }
        public int id_otro { get; set; }
        public string Nom_cor_emp { get; set; }
        public string tipo_nov { get; set; }
        public Nullable<long> monto { get; set; }
        public string empleado { get; set; }
    }
}
